CREATE TABLE CLIENT (
  ID       BIGINT IDENTITY CONSTRAINT PK_USER PRIMARY KEY,
  LOGIN    VARCHAR(32)  NOT NULL,
  PASSWORD VARCHAR(128) NOT NULL,
  GENDER   CHAR CHECK (GENDER IN ('M', 'F'))
);

CREATE TABLE CATEGORY (
  ID   BIGINT IDENTITY CONSTRAINT PK_CATEGORY PRIMARY KEY,
  NAME VARCHAR(32)
);

CREATE TABLE RECORD (
  ID            BIGINT IDENTITY CONSTRAINT PK_RECORD PRIMARY KEY,
  CLIENT_ID     BIGINT  NOT NULL,
  CATEGORY_ID   BIGINT  NOT NULL,
  TYPE          VARCHAR(8) CHECK (TYPE IN ('INCOME', 'EXPENDITURE')),
  PRICE         INTEGER NOT NULL CHECK (PRICE > 0),
  DESCRIPTION   VARCHAR(256),
  CREATION_DATE DATE    NOT NULL,

  CONSTRAINT FK_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)
    ON DELETE CASCADE,
  CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
    ON DELETE CASCADE
);